- charts/simple-deployment/Chart.yaml
- charts/simple-deployment/templates/deployment.yaml
- charts/simple-deployment/values.yaml
Useful for stuff like datadog for getting tags for environment.
> Added fieldRefEnvironment

- charts/simple-deployment/Chart.yaml
- charts/simple-deployment/templates/deployment.yaml
Fixed: Dublicate liveness probe in deployment manifest. 
https://github.com/ok-amba/default-ok-charts/blob/simple-deployment-0.6.2/charts/simple-deployment/templates/deployment.yaml#L75-L79
> fix: dublicate liveness probe in deployemt

- charts/devx-dashboard/Chart.yaml
Fixes a issue that looks for the wrong property in the JWT token, when looking for a username in scenarios when dead-letters are updated.
> feat: Release DevX 1.0.6

- charts/simple-deployment/Chart.yaml
- charts/simple-deployment/templates/_helpers.tpl
- charts/simple-deployment/templates/deployment.yaml
- charts/simple-deployment/templates/ingress.yaml
- charts/simple-deployment/templates/service.yaml
All label values are now quoted.
> fix: added quotes on all label values

- charts/datadog-monitor/README.md
- charts/datadog-monitor/templates/_helpers.tpl
- charts/datadog-monitor/templates/monitor.yaml
- charts/datadog-monitor/values.yaml
> fix: optimized datadog release candidate

- charts/datadog-monitor/Chart.yaml
- charts/datadog-monitor/templates/monitor.yaml
Changed default settings to reflect actual default settings in datadog UI.
promoted to stable version 0.1.0
> fix: changed default settings

- charts/datadog-monitor/Chart.yaml
- charts/datadog-monitor/README.md
- charts/datadog-monitor/templates/_helpers.tpl
- charts/datadog-monitor/templates/monitor.yaml
- charts/datadog-monitor/values.yaml
> New Chart: Datadog Monitor

- charts/datadog-monitor/Chart.yaml
- charts/datadog-monitor/README.md
- charts/datadog-monitor/templates/monitor.yaml
- charts/datadog-monitor/values.yaml
- Removed duplicate `name` field in `values.yaml`.
- Made `noDataTimeframe` option field conditional.
- Updated examples on readme.
> fix: removed duplicate name field in values + chores

- charts/simple-deployment/values.yaml
Reduced requested memory from `1000Mi` to `500Mi` and CPU from `400m` to `100m`.
> fix: reduced requested cpu and mem as default value.

- charts/simple-deployment/Chart.yaml
- charts/simple-deployment/templates/deployment.yaml
- charts/simple-deployment/values.yaml
> feature: support for envFrom configmap.

- charts/db-migration/Chart.yaml
- charts/db-migration/templates/job.yaml
> fix: datadog log annotation on job

- charts/db-migration/Chart.yaml
- charts/db-migration/templates/_helpers.tpl
Enabled health check endpoint on the cloud sql proxy.
> feat: added health check to sql proxy

- charts/cronjob/Chart.yaml
- charts/cronjob/templates/cronjob.yaml
- charts/cronjob/values.yaml
Add the configmaps to cronjob just as it was for simple deployment.
> feat: Add support for envFrom configmaps.

- charts/cronjob/templates/cronjob.yaml
- charts/cronjob/values.yaml
Fixes #60
Added support for activeDeadlineSeconds on jobs.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup
> feat: added support for activeDeadlineSeconds on cronjob

- .gitignore
- charts/devx-dashboard/Chart.yaml
- charts/devx-dashboard/templates/_helpers.tpl
- charts/devx-dashboard/templates/backend-dead-letter-deployment.yaml
- charts/devx-dashboard/templates/backend-dead-letter-iam-policies.yaml
- charts/devx-dashboard/templates/backend-dead-letter-job.yaml
- charts/devx-dashboard/templates/backend-dead-letter-service.yaml
- charts/devx-dashboard/templates/backend-release-board-deployment.yaml
- charts/devx-dashboard/templates/backend-release-board-service.yaml
- charts/devx-dashboard/templates/configmap-appsettings.yaml
- charts/devx-dashboard/templates/frontend-deployment.yaml
- charts/devx-dashboard/templates/frontend-ingress.yaml
- charts/devx-dashboard/values.yaml
- Changed port from 80 to 8080 on deployments to support .NET 8
- Updated iam-service-account to 2.0.0 which now supports Workload Identity
- Removed db-migration dep and implemented it into the chart to gain more control.
- Refactored the values.yaml file.
- Added hardened security settings to deployments.
- Updated sqlinstance dep to 3.0.0
- Updated SQL Cloud Proxy to 2.8
> feat: devx major update 2 0 0

- charts/devx-dashboard/Chart.yaml
- charts/devx-dashboard/README.md
- charts/devx-dashboard/values.yaml
Fixed minor issue with the sqlinstance values.
Added example to README.md
> fix: sqlinstance values

- charts/devx-dashboard/Chart.yaml
- charts/devx-dashboard/templates/backend-dead-letter-service.yaml
- charts/devx-dashboard/templates/backend-release-board-service.yaml
- charts/devx-dashboard/templates/frontend-deployment.yaml
- charts/devx-dashboard/templates/frontend-ingress.yaml
- Changed service port for backend from ` 80` to `8080`.
- Added the `AZURE_AUTH_ENDPOINT` environment variable to the frontend.
- Added capabilities to the frontend deployment.
- Updated appVersion to `2.0.10`
> fix: final updates to devx board

- charts/legend-deployment/.helmignore
- charts/legend-deployment/Chart.yaml
- charts/legend-deployment/README.md
- charts/legend-deployment/templates/_helpers.tpl
- charts/legend-deployment/templates/deployment.yaml
- charts/legend-deployment/templates/grafana-dashboards.yaml
- charts/legend-deployment/templates/ingress-gatekeeper.yaml
- charts/legend-deployment/templates/ingress.yaml
- charts/legend-deployment/templates/podmonitor.yaml
- charts/legend-deployment/templates/service-gatekeeper.yaml
- charts/legend-deployment/templates/service.yaml
- charts/legend-deployment/values.yaml
Added legend-deployment chart to default-ok-chart repo.
Copied directly from helm-legend-deployment repo in azure devops. Specific deployments was not copied as they're not suited for a public repo.
> Added legend-deployment to default-ok-charts

- charts/simple-deployment/Chart.yaml
- charts/simple-deployment/templates/pdb.yaml
Update kind from "PodDistruptionBudget" to "PodDisruptionBudget"
> Fix: Fix typo in kind 

- charts/legend-deployment/README.md
- charts/simple-deployment/README.md
Add examples to showcase the possibility to utilize External Secret Store to access secrets in google
> Add ESS Example

- catalog-info.yaml
This PR is due to Backstage needing this file for discovering the repository, and I would like to see how it works. FREESTYLE YEEEEAH
> feat: adding catalog-info.yaml for backstage test

- charts/cronjob/Chart.yaml
- charts/cronjob/templates/_helper.tpl
- charts/db-migration/Chart.yaml
- charts/db-migration/templates/_helpers.tpl
- charts/devx-dashboard/Chart.yaml
- charts/devx-dashboard/templates/backend-dead-letter-deployment.yaml
- charts/devx-dashboard/templates/backend-dead-letter-job.yaml
- charts/legend-deployment/Chart.yaml
- charts/legend-deployment/templates/_helpers.tpl
- charts/simple-deployment/Chart.yaml
- charts/simple-deployment/templates/_helpers.tpl
Updates Cloud SQL proxy to address CVE vulnerabilities.
Resolves Azure DevOps task 113004
> fix: update Cloud SQL proxy 2.14.0 → 2.17.1 for CVE fix

- charts/simple-deployment/README.md
Simple-deployment: small readme fixes
> Simple-deployment: small readme fixes
