ok-amba/default-ok-charts

charts/simple-deployment/templates/deployment.yaml
charts/simple-deployment/values.yaml

Datadog annotations and labels can now be enabled on the simple-deployment chart.

Added datadog logging for deployment.

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/templates/ingress.yaml

External DNS now does label filtering. The `external-dns.alpha.kubernetes.io/hostname` annotation is now replaced with `external-dns-create` label instead. 
No change needed to upgrade.

fix: replaced external-dns annotation with label

---

charts/devx-dashboard/Chart.yaml
charts/devx-dashboard/templates/_helpers.tpl
charts/devx-dashboard/templates/backend-dead-letter-deployment.yaml
charts/devx-dashboard/templates/backend-release-board-deployment.yaml
charts/devx-dashboard/templates/frontend-deployment.yaml
charts/devx-dashboard/values.yaml

Image tags on portal, release and deadletter modules are now defaulted to `appVersion` in `Chart.yaml`.
You can override the tag in each module in the `values.yaml` file.

feat: DevX images versions defaults to Chart.yaml appVersion

---

charts/devx-dashboard/Chart.yaml

This release contains a fix to the OpenTelemetry metrics included in the application - primarily for the Datadog exporter.

feat: Updated DevX to 1.0.5

---

charts/datadog-monitor/templates/monitor.yaml

The metadata name on Datadog Monitor objects are now converted to lowercase

fix: metadata name converted to lowercased

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/README.md
charts/simple-deployment/templates/_helpers.tpl
charts/simple-deployment/templates/deployment.yaml
charts/simple-deployment/templates/ingress.yaml
charts/simple-deployment/values.yaml

- Cloud SQL Proxy
- Updated to major version 2.
- Supports Workload Identity.
- `region` and `imageTag` are now hidden defaults
- `projectId` field is moved to `global` block and renamed to `projectID`. 
- Opt-in SSL rules on ingress configuration
- Rarely used fields in `values.yaml` are now hidden defaults.
- DataDog tracing configuration support removed.
- Default secrityContext added on main container.
- If the `deployment.cloudSQLProxy.imageTag` major version is less than 2, the chart will not template.
- SSL Redirection is disabled by default on the ingress. You must explicitly enable it on the ingress configuration.

release: simple-deployment 1.0.0

---

charts/cronjob/Chart.yaml
charts/cronjob/templates/_helper.tpl
charts/cronjob/templates/cronjob.yaml
charts/cronjob/values.yaml

A Kubernetes Cronjob chart with support for Cloud SQL Proxy. The Cloud SQL Proxy is started with the `--quitquitquit` parameter which enables a http endpoint on port 9091 only reachable from localhost. When the the job is finished just send a POST request to `http://localhost:9091/quitquitquit` to kill the process.

New chart: Kubernetes Cronjob

---

charts/cronjob/Chart.yaml
charts/cronjob/templates/cronjob.yaml
charts/cronjob/values.yaml

Changed the default values for `job.restartPolicy` to `Never`. The `Always` value is not supported for CronJobs.

cronjob: changed default restartPolicy to Never

---

charts/cronjob/Chart.yaml
charts/cronjob/templates/_helper.tpl

The `chart-name` label is set to `cronjob` instead of `{{ .Chart.Name }}`. This is because the Chart name changes if you're using an alias on the dependency property.

cronjob: chart-name label is set to cronjob instead of .Chart.Name

---

charts/db-migration/Chart.yaml
charts/db-migration/templates/_helpers.tpl
charts/db-migration/templates/job.yaml
charts/db-migration/values.yaml

- ArgoCD config is now hidden defaults
- DataDog logs are now disabled by default
- Removed `shareProcessNamespace` option
- Added `envFromConfigmap` and `fieldRefEnvironment` options
- Added support for Google Workload Identity (Still supports a credentials file)
- Updated Cloud SQL Proxy to version 2
- Includes structured logs
- Is started with the `--quitquitquit` parameter
Cloud SQL Proxy version 2 now supports the `--quitquitquit` parameter, which means that when the migration job is done, you can send a POST request to `http://localhost:9091/quitquitquit` to terminate the Cloud SQL Proxy process. If not the job will continue to run.

db-migration: major version release v1.0.0

---

charts/db-migration/templates/_helpers.tpl
charts/db-migration/values.yaml

Added a check for setting the Cloud SQL Proxy `imageTag`. The templating will fail if major version is below 2.

fix: added imageTag check for sql proxy

---

charts/simple-deployment/templates/_helpers.tpl

The `chart-name` label is changed from `.Chart.Name` to `simple-deployment`.
The reason for this is that if the chart is given an alias the `.Chart.Name` is changed to that alias.

fix: set static chart-name label

---

charts/cronjob/Chart.yaml
charts/cronjob/templates/_helper.tpl

Enabled health check endpoint on the cloud sql proxy for Cronjob chart.

feat: cronjob added health check to sql proxy

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/templates/deployment.yaml

I have made an update so we now can include a `subPath` to a `volumeMounts` if we only want to mount a single file into a given known folder.
This has been tested locally with:
**Chart.yaml**
```yaml
apiVersion: v2
name: testsubpathjob
description: A test job for testing subpath
version: 0.1.0
dependencies:
- name: simple-deployment
version: 1.0.2
```
**values.yaml**
```yaml
global:
projectID: knp-emobility-test
simple-deployment:
deployment:
replicas: 3
container:
environment:
APPSETTINGS_SELECTOR: test
configMaps:
- name: hubject-certificates
mountPath: /certs
- name: environment-configmap
mountPath: /app/appsettings.cloud.json
subPath: appsettings.cloud.json
- name: environment-test-configmap
mountPath: /app/appsettings.cloud.test.json
subPath: appsettings.cloud.test.json
```
which …

feat: support for subpaths on configmap volume mounts

---

charts/cronjob/Chart.yaml
charts/cronjob/templates/cronjob.yaml

I have added the ability to add a `subPath` for `configMaps`. This has been tested locally, with this
**Chart.yaml**
```yaml
apiVersion: v2
name: testsubpathjob
description: A test job for testing subpath
version: 0.1.0
dependencies:
- name: cronjob
version: 0.1.5
repository: file://../../charts/cronjob
```
**values.yaml**
```yaml
global:
projectID: knp-emobility-test
cronjob:  
job:
replicas: 3
container:
environment:
APPSETTINGS_SELECTOR: test
configMaps:
- name: hubject-certificates
mountPath: /certs
- name: environment-configmap
mountPath: /app/appsettings.cloud.json
subPath: appsettings.cloud.json
- name: environment-test-configmap
mountPath: /app/appsettings.cloud.test.json
subPath: appsettings.cloud.test.json
```
which produces this, when running `helm template .`:
```yaml
--- …
```

feat: Added the ability to add a `subPath` to `volumeMounts` for a cronjob

---

charts/cronjob/templates/cronjob.yaml

The template function `default` is preventing the usage of `backoffLimit: 0` because the default value is used if the value given is `null`, `false`, `0` or empty string/array.
Removed `default` function. The default value is already defined in the `values.yaml` file so it will not change anything.

fix: removed default func for backoffLimit prop

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/templates/ingress.yaml
charts/simple-deployment/values.yaml

The `.ingress.ingressClassName` property on the ingress def was removed in `1.0`. The `wwwRedirect`  feature was dependent on that and therefore would always evaluate to false.

fix: www redirect issue caused be faulty if statement

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/templates/_helpers.tpl

Added `--structured-logs` and `--health-check` arguments on the Cloud SQL Proxy in the `simple-deployment` chart. Also bumped the tag of the image to `2.7`.

feat: added health check and structured logs args to cloud sql proxy

---

charts/cronjob/Chart.yaml
charts/cronjob/values.yaml

Changed the following default setting.
- `successfulJobsHistroyLimit: 2`
- `concurrencyPolicy: Forbid`
-  `ttlSecondsAfterFinished: 172800`  "*2 days*"
- `resources.requests:`
- `memory: 500Mi`
- `cpu: 100m`
- `resources.limits:`
- `memory: 1000Mi`
- `cpu: 500m`

feat: updated deafault settings

---

charts/datadog-monitor/Chart.yaml
charts/datadog-monitor/values.yaml

Removed the `projectName` property since it is not in use.

fix: Remove unused parameter project name datadog monitor

---

charts/devx-dashboard/Chart.yaml
charts/devx-dashboard/values.yaml

Add an option to enable googleSecretManager in the Devx Portal

feat: Add GoogleSecretManager to Devx helm chart

---

charts/nats-streaming/Chart.yaml
charts/nats-streaming/templates/_helpers.tpl
charts/nats-streaming/templates/serviceMonitor.yaml
charts/nats-streaming/templates/validation-checks.yaml
charts/nats-streaming/values.yaml

Previously the nats-conf used `$.Release.Namespace` to set the cluster routes. This would prevent the cluster from connecting to each other, since DNS resolution would fail. DNS resolution fails, since we run a `helm template` in our pipelines, which makes `$.Release.Namespace` resolve to `default`. 
This PR introduces a new required property in `values.yaml` that allows setting the kubernetes namespace explicitly.

nats-streaming (fix): Set kubernetes namespace explicitly  to fix cluster routes DNS resolution. 

---

charts/nats-streaming/Chart.yaml
charts/nats-streaming/templates/nodePort.yaml
charts/nats-streaming/templates/validation-checks.yaml
charts/nats-streaming/values.yaml

The on-prem legacy cluster exposed NATS to G4 through NodePort services. 
I have tried with a LoadBalancer service, but it does not seem like we have any LoadBalancer capabilities deployed to the cluster such as MetalLB.

[Release candidate 3] nats-streaming (feat): Add support for enabling NodePort 

---

charts/legend-deployment/Chart.yaml
charts/legend-deployment/templates/additionalIngress.yaml
charts/legend-deployment/tests/additionalIngress_test.yaml
charts/legend-deployment/values.yaml

The following PR introduces support for multiple hosts in an additional opt-in Ingress object that uses the Cloudflare DNS ClusterIssuer for certificates. 
The change is required to handle routing and certificates for the "old" URLs for the services that are being migrated from legacy cluster to Gen2 / shiny cluster. 
I have currently verified the following: 
* Legend-deployment can deploy to cluster with additional Ingress
* Requests using a host under `additionalHosts` routes to the expected pod
* Cloudflare DNS ClusterIssuer issues a certificate as expected:

Legend-deployment: Support multiple hosts for Ingress

---

charts/nats-streaming/.helmignore
charts/nats-streaming/Chart.yaml
charts/nats-streaming/README.md
charts/nats-streaming/templates/_helpers.tpl
charts/nats-streaming/templates/configmap.yaml
charts/nats-streaming/templates/initdb.yaml
charts/nats-streaming/templates/nats-configmap.yaml
charts/nats-streaming/templates/nodePort.yaml
charts/nats-streaming/templates/pvc.yaml
charts/nats-streaming/templates/service.yaml
charts/nats-streaming/templates/serviceMonitor.yaml
charts/nats-streaming/templates/statefulset.yaml
charts/nats-streaming/templates/validation-checks.yaml
charts/nats-streaming/values.yaml

I noticed the NATS instance in "ansoegning" namespace trying to connect to peers in the "cardservice" namespace. I suspect this is caused by using the same instance name and possible something with the `cluster_advertise` setting?
This PR disables `cluster_advertise ` and makes the namespace part of "stan.name"

nats-streaming-rc4: Include namespace in stan.name and disable cluster_advertise

---

charts/legend-deployment/Chart.yaml
charts/legend-deployment/templates/additionalIngress.yaml
charts/legend-deployment/tests/additionalIngress_test.yaml
charts/legend-deployment/values.yaml

Adds an additional ingress object for supporting old "ok.dk" URLs during migration

(feat) Legend-Deployment: Add additional ingress for legend-deployment

---

charts/nats-streaming/.helmignore
charts/nats-streaming/Chart.yaml
charts/nats-streaming/README.md
charts/nats-streaming/templates/_helpers.tpl
charts/nats-streaming/templates/configmap.yaml
charts/nats-streaming/templates/externalsecret.yaml
charts/nats-streaming/templates/initdb.yaml
charts/nats-streaming/templates/nats-configmap.yaml
charts/nats-streaming/templates/nodePort.yaml
charts/nats-streaming/templates/pvc.yaml
charts/nats-streaming/templates/service.yaml
charts/nats-streaming/templates/serviceMonitor.yaml
charts/nats-streaming/templates/statefulset.yaml
charts/nats-streaming/templates/validation-checks.yaml
charts/nats-streaming/tests/externalsecret_test.yaml
charts/nats-streaming/tests/validation-checks_test.yaml
charts/nats-streaming/values.yaml

Quick overview over changes that deviate from the "stan" chart that this chart is a fork of (https://github.com/nats-io/k8s/tree/main/helm/charts/stan) 
Adds the following new properties: 
- `kubernetesNamespace`
- `stan.auth.secretRef`
- `nodePort`
The `kubernetesNamespace` property is added because it is required for the internal DNS routing to work in `nats-configmap.yaml`. `nats.clusterRoutes` is defined in `helpers.tpl`. The cluster nodes were not able to connect to its peers in the cluster without this property. 
The `stan.auth.secretRef` enables specifying of auth credentials through a secret. Originally the chart only supported specifying the credentials through clear text in the `values.yaml` file. This feature also supports creation of an `ExternalSecret` object. 
The `nodePort` …

nats-streaming: Add fork of "stan" Helm Chart 

---

charts/db-migration/Chart.yaml
charts/db-migration/templates/job.yaml
charts/db-migration/tests/job_test.yaml

Fixed  bug where following the comments in the `values.yaml` file for `job.imagePullSecrets` would cause a failure, since it does not follow the Kubernetes spec when templated.

(fix) db-migration: Fix image pull secrets

---

charts/db-migration/templates/job.yaml

Last released failed to publish chart to the gh pages Helm repository for some reason...

db-migration: Rerelease DB Migration 1.1.1

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/README.md
charts/simple-deployment/templates/_helpers.tpl
charts/simple-deployment/templates/ingress.yaml
charts/simple-deployment/tests/ingress_test.yaml

- New defaults for ingressClassName.
- without breaking backwards compatibility in GCP cloud.
- without breaking support for overwriting ingressClassName in the services' values file.
- with private by default on Gen 2 kubernetes platform and support for public to comply with CISO.
- with public by default in GKE cloud platform, and private not supported.
- The boolean is not set by default in global values, to support different default in GCP and on premises.
- The cluster-issuer is adapting to the cluster your service is deployed in. 
- This PR includes unittests for the differents cases that we now support in Simple-deployment. 
- The different scenarios in this release have been tested in dev release 
- --version 2.3.0-a15d463902c294ad9c3c5e9793e994b5968dc72b
- The readme has been …

Default ingress pjuu

---

charts/legend-deployment/Chart.yaml
charts/legend-deployment/README.md
charts/legend-deployment/templates/_helpers.tpl
charts/legend-deployment/templates/ingress.yaml
charts/legend-deployment/tests/ingress_test.yaml

- New defaults for ingressClassName.
- Without breaking support for overwriting ingressClassName in the services' values file.
- With private by default on Gen 2 kubernetes platform and support for public to comply with CISO.
- The boolean is not set by default in global values, to support different default in GCP and on premises.
- Support for ok.dk and okdc.dk public and private domain names.
- The cluster-issuer is adapting to the cluster your service is deployed in.
- This PR includes unittests for the different cases that we now support in Legend-deployment.
- The different scenarios in this release have been tested in templates.
- The readme has been updated to explain support for private ingress. Also showing how to make your service public on Gen 2.

feat: Added support for private ingress - Helm unittests included

---

charts/simple-deployment/README.md

The documentation now states that external secrets only works in gen2.

Update externalsecret documentation

---

charts/simple-deployment/Chart.yaml
charts/simple-deployment/values.yaml

As per request from our developers. The exposure and cluster parameters should be included in the default values.yaml file for simple-deployment. That way they know what minimum parameters they have to include in order when creating a helm chart for their service.
https://dev.azure.com/okamba/Infrastruktur/_boards/board/t/Infrastruktur%20-%20Platform/Stories?text=simple-de&workitem=113739

113739: feature: include exposure and cluster as parameters in default values

---

charts/legend-deployment/Chart.yaml
charts/legend-deployment/templates/external-secret-ref.yaml
charts/legend-deployment/templates/external-secret.yaml
charts/nats-streaming/Chart.yaml
charts/nats-streaming/templates/externalsecret.yaml
charts/simple-deployment/Chart.yaml
charts/simple-deployment/templates/external-secret.yaml

This PR has spawned due to: 
https://dev.azure.com/okamba/Infrastruktur/_boards/board/t/Infrastruktur%20-%20Platform/Stories?System.AssignedTo=%40me%2C_Unassigned_&workitem=113396
We are on ESO version 0.16.2
The beta API is being deprecated from 0.17.x onwards. 
The ESO version we are on supports the GA API.
Should have 0 consequences at the time of implementation. 
When the ESO is bumped to 0.17.0+ the support for the beta api is gone, so we need to inform the developers that they need to bump to the version of the charts thats created when this change is deployed, in order for their ExternalSecrets to work just as before.

chore: bump external-secret apiversion from beta to ga
